### ISSUE TITLE
RE: Dataset Download Corrupt ZIP file error

### ISSUE THREAD

**Issue by danieleceUL** [MoyoG/FishEye8K#2]
To whom it may concern:-

I tried downloading the dataset from the website but when I try extracting the images, I get a corrupt file error:
![image](https://github.com/MoyoG/FishEye8K/assets/113525778/185ae0e8-0d5a-40a0-b362-414e0b358101)

**Comment by pingyang1117** [comment]
Ya.. if the zip file is larger than 4GB, standard zip tools such as unzip on Ubuntu might not be able to handle it correctly, causing errors or corruption.

You can install 7-zip on Ubuntu by running the following command in the terminal:
`sudo apt-get install p7zip-full`

Then you can extract your zip file with 7z command:
`7z x Fisheye8K.zip -o./Fisheye8K`
