### ISSUE TITLE
the data can not be download

### ISSUE THREAD

**Issue by wuyinglong123** [MoyoG/FishEye8K#5]
the dataset called "Fisheye8K_all dataset renew version. including_train&test 2024 Jan Update" can not be unzipped.

**Comment by Omunkhuush** [comment]
![image](https://github.com/MoyoG/FishEye8K/assets/73123564/fd645801-c347-4f40-be9e-fc2df8795ea8)
if you are using a Linux OS terminal, you can use 7z library to extract the downloaded file.

apt install p7zip-full
7z x nchcproxy
