### ISSUE TITLE
Please tell me about the training procedure

### ISSUE THREAD

**Issue by yvnneno003** [MoyoG/FishEye8K#6]
Refer to the Hyperparameters and Data preprocessing written in your paper,I use the yolov8 model Version YOLOv8x to train FishEye8K and have been unable to get the Precision and Recall to reach 0.8418 and 0.3665 written in your paper.
I use the command line to training. Did you write a program to do the training? Can you tell me how you did it? Are there any steps?

**Comment by Omunkhuush** [comment]
could you check conf_thres and iou_thres values. our config is conf_thres=0.5 iou_thres=0.5

**Comment by yvnneno003** [comment]
Yes, I have used this parameter to execute the training  command, but the effect is still not as good as the values ​​​​in the paper. I wonder if there are any questions about my training  command?

yolo task=detect mode=train data=coco128-FishEye8K.yaml model=yolov8x-p6-FishEye8K.yaml pretrained=yolov8x.pt epochs=250 optimizer=Adam conf=0.5 iou=0.5 imgsz=640 batch=12 device=1 project=FishEye8K name=y8x6-FishEye8K_1920
