### ISSUE TITLE
Hyperparameters for fisheye

### ISSUE THREAD

**Issue by Fritskee** [MoyoG/FishEye8K#7]
Hello, 

Thanks for sharing this dataset. I'm wondering for training the Yolo-v8 model you changed any of the default hyperparameters or not? I'm also wondering if you de-warp the images before training a model?

Kind regards

**Comment by Omunkhuush** [comment]
Hello,

We didn't change any hyperparameters for training the YOLOv8 model. Additionally, we did not de-warp the images before training.

Best regards.
