### ISSUE TITLE
Dataset zip damaged

### ISSUE THREAD

**Issue by daniel-bogdoll** [MoyoG/FishEye8K#8]
Hey everyone,

I was interested in using your dataset. However, after downloading the latest version (Fisheye8K_all_including_train&test_update_2024Jan Update.zip) I cannot unzip it:

![image](https://github.com/user-attachments/assets/e49fa01a-0f7d-47b3-81c3-15fdbd5a8278)

Running ```zip -FF corrupted.zip --out new.zip``` to fix the corruption did work, but I cannot be certain if the dataset now is fully as intended. After unzipping, I have ```24,012 items, totalling 14.4 GB```. 

Could you double check if the link you provide can be replaced with a fully working zip archive?

**Comment by nhattan417** [comment]
Hi, please check #2 for unzipping.

**Comment by daniel-bogdoll** [comment]
Ah. Thanks!
